"""Purchase marketPlace

Revision ID: 1a3e1d00845c
Revises: 568fe40480be
Create Date: 2022-02-14 19:46:40.344926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3e1d00845c'
down_revision = '568fe40480be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tpurchase', sa.Column('marketPlaceId', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('FK_tpurchase_marketPlaceId'), 'tpurchase', 'mmarketplace', ['marketPlaceId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('FK_tpurchase_marketPlaceId'), 'tpurchase', type_='foreignkey')
    op.drop_column('tpurchase', 'marketPlaceId')
    # ### end Alembic commands ###
