"""Item Image

Revision ID: 568fe40480be
Revises: 95ba819cbcd6
Create Date: 2022-02-10 18:22:25.310330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568fe40480be'
down_revision = '95ba819cbcd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mitemimg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemId', sa.Integer(), nullable=False),
    sa.Column('contentType', sa.String(length=50), nullable=True),
    sa.Column('content', sa.LargeBinary(length=10000000), nullable=True),
    sa.Column('originalFileName', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['itemId'], ['mitem.id'], name=op.f('FK_mitemimg_itemId'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mitemimg')
    # ### end Alembic commands ###
