"""Purchase and Sales

Revision ID: 95ba819cbcd6
Revises: a8f99bd5b4e4
Create Date: 2022-01-19 11:12:23.678844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ba819cbcd6'
down_revision = 'a8f99bd5b4e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mmarketplace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('isActive', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tpurchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name=op.f('Idx_tpurchase_code'))
    )
    op.create_index('Idx_date', 'tpurchase', ['date'], unique=False)
    op.create_table('tsales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('marketPlaceId', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['marketPlaceId'], ['mmarketplace.id'], name=op.f('FK_tsales_marketPlaceId')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name=op.f('Idx_tsales_code'))
    )
    op.create_index('Idx_date', 'tsales', ['date'], unique=False)
    op.create_table('tpurchased',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchaseId', sa.Integer(), nullable=False),
    sa.Column('itemId', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('unitPrice', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.ForeignKeyConstraint(['itemId'], ['mitem.id'], name=op.f('FK_tpurchased_itemId')),
    sa.ForeignKeyConstraint(['purchaseId'], ['tpurchase.id'], name=op.f('FK_tpurchased_purchaseId'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tsalesd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salesId', sa.Integer(), nullable=False),
    sa.Column('itemId', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('unitPrice', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.ForeignKeyConstraint(['itemId'], ['mitem.id'], name=op.f('FK_tsalesd_itemId')),
    sa.ForeignKeyConstraint(['salesId'], ['tsales.id'], name=op.f('FK_tsalesd_salesId'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('titemjournal', sa.Column('salesDId', sa.Integer(), nullable=True))
    op.add_column('titemjournal', sa.Column('purchaseDId', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('FK_titemjournal_purchaseDId'), 'titemjournal', 'tpurchased', ['purchaseDId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('FK_titemjournal_salesDId'), 'titemjournal', 'tsalesd', ['salesDId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('FK_titemjournal_salesDId'), 'titemjournal', type_='foreignkey')
    op.drop_constraint(op.f('FK_titemjournal_purchaseDId'), 'titemjournal', type_='foreignkey')
    op.drop_column('titemjournal', 'purchaseDId')
    op.drop_column('titemjournal', 'salesDId')
    op.drop_table('tsalesd')
    op.drop_table('tpurchased')
    op.drop_index('Idx_date', table_name='tsales')
    op.drop_table('tsales')
    op.drop_index('Idx_date', table_name='tpurchase')
    op.drop_table('tpurchase')
    op.drop_table('mmarketplace')
    # ### end Alembic commands ###
