"""Items tables

Revision ID: a8f99bd5b4e4
Revises: 
Create Date: 2022-01-10 12:45:56.306955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f99bd5b4e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mitemcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('isActive', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('categoryId', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sellingPrice', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('isActive', sa.Boolean(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['mitemcategory.id'], name=op.f('FK_mitem_categoryId')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name=op.f('Idx_mitem_code'))
    )
    op.create_table('titemjournal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemId', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('journalType', sa.Enum('Initial Stock', 'Buy', 'Sell', 'Correction', 'Ending Balance'), nullable=False),
    sa.Column('refCode', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['itemId'], ['mitem.id'], name=op.f('FK_titemjournal_itemId')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('Idx_itemId_date', 'titemjournal', ['itemId', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('Idx_itemId_date', table_name='titemjournal')
    op.drop_table('titemjournal')
    op.drop_table('mitem')
    op.drop_table('mitemcategory')
    # ### end Alembic commands ###
